version: '3.8'

services:

  # PHP Apache
  php-apache:
    build: ./config/php
    ports:
      - 8055:80
    volumes:
      - ./html:/var/www/html
    restart: always
    depends_on:
      - mysql

  # MySQL
  mysql:
    build: ./config/mysql
    ports:
      - 3307:3306
    volumes:
      - ./config/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

  #Mail
  mail:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
    volumes:
      - ./maildir:/tmp
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp